"1": 
  ip: "127.0.0.1"
  port: 50514
  shell_number: 6

"2": 
  ip: "127.0.0.1"
  port: 50514
  shell_number: 7
  
"3": 
  ip: "127.0.0.1"
  port: 50514
  shell_number: 1

"4": 
  ip: "127.0.0.1"
  port: 50514
  shell_number: 8

"5": 
  ip: "127.0.0.1"
  port: 50514
  shell_number: 2

"6": 
  ip: "127.0.0.1"
  port: 50514
  shell_number: 3
